{
    ["glow"] = false,
    ["color"] = {
        [1] = 1,
        [2] = 1,
        [3] = 1,
        [4] = 1,
    },
    ["customText"] = "function()\\n    \\n    -- Never Surrender\\n    local curHP = UnitHealth(\\\"player\\\")\\n    local maxHP = UnitHealthMax(\\\"player\\\")\\n    local percHPMissing = (maxHP - curHP) / maxHP\\n    local _, _, _, hasNS = GetTalentInfo(4, 2, 1)\\n    local NSPerc = hasNS and (1 + percHPMissing) or 1\\n    \\n    local currentIP = select(16, WA_GetUnitBuff(\\\"player\\\", 190456)) or 0\\n    \\n    local castIP = tonumber((GetSpellDescription(190456):match(\\\"%%.+%d\\\"):gsub(\\\"%D\\\",\\\"\\\"))) * NSPerc or 0\\n    \\n    local IPCap = math.floor(castIP * 1.3)\\n    if aura_env.hasBloodsport then\\n        IPCap = math.floor(castIP * 1.295)\\n    end\\n    \\n    if IPCap - currentIP == -1 or IPCap - currentIP == -2 then\\n        IPCap = currentIP\\n    end\\n    \\n    local percentOfCap = currentIP / IPCap * 100\\n    percentOfCap = aura_env.shortenPercent(percentOfCap)\\n    \\n    local additionalAbsorb = IPCap - currentIP\\n    \\n    local percentOfMaxHP = currentIP / UnitHealthMax(\\\"player\\\") * 100\\n    percentOfMaxHP = aura_env.shortenPercent(percentOfMaxHP)\\n    \\n    if aura_env.config.iconOptions.saturateBasedOnRage then\\n        \\n        if UnitPower(\\\"player\\\") >= GetSpellPowerCost(190456)[1].cost then\\n            aura_env.region:SetDesaturated(false)\\n        else\\n            aura_env.region:SetDesaturated(true)\\n        end\\n        \\n    else\\n        \\n        if currentIP == 0 then\\n            aura_env.region:SetDesaturated(true)\\n        else\\n            aura_env.region:SetDesaturated(false)\\n        end\\n    end\\n    \\n    if (currentIP + castIP <= IPCap) or ((IPCap - currentIP) / castIP >= aura_env.config.textOptions.thresholdPerc) then -- full cast\\n        \\n        aura_env.setVisuals(aura_env.config.textOptions.fullCastColor[1],aura_env.config.textOptions.fullCastColor[2],aura_env.config.textOptions.fullCastColor[3],aura_env.config.textOptions.fullCastColor[4],\\n        aura_env.config.iconOptions.glowCondition == 2 or aura_env.config.iconOptions.glowCondition == 4)\\n        \\n    elseif IPCap - currentIP > 0 then -- cap cast\\n        \\n        aura_env.setVisuals(aura_env.config.textOptions.capColor[1],aura_env.config.textOptions.capColor[2],aura_env.config.textOptions.capColor[3],aura_env.config.textOptions.capColor[4],\\n        aura_env.config.iconOptions.glowCondition == 3 or aura_env.config.iconOptions.glowCondition == 4)\\n        \\n    elseif IPCap - currentIP <= 0 then -- clip cast\\n        \\n        aura_env.setVisuals(aura_env.config.textOptions.clipColor[1],aura_env.config.textOptions.clipColor[2],aura_env.config.textOptions.clipColor[3],aura_env.config.textOptions.clipColor[4], false)\\n    end\\n    \\n    if aura_env.config.textOptions.shortenText then\\n        currentIP = aura_env.shortenNumber(currentIP)\\n        additionalAbsorb = aura_env.shortenNumber(additionalAbsorb)\\n    end\\n    \\n    local text1 = \\\"\\\"\\n    \\n    if aura_env.config.textOptions.text1 == 1 then\\n        text1 = currentIP\\n    elseif aura_env.config.textOptions.text1 == 2 then\\n        text1 = percentOfCap\\n    elseif aura_env.config.textOptions.text1 == 3 then\\n        text1 = additionalAbsorb\\n    elseif aura_env.config.textOptions.text1 == 4 then\\n        text1 = percentOfMaxHP\\n    end\\n    \\n    local text2 = \\\"\\\"\\n    \\n    if aura_env.config.textOptions.text2 == 1 then\\n        text2 = currentIP\\n    elseif aura_env.config.textOptions.text2 == 2 then\\n        text2 = percentOfCap\\n    elseif aura_env.config.textOptions.text2 == 3 then\\n        text2 = additionalAbsorb\\n    elseif aura_env.config.textOptions.text2 == 4 then\\n        text2 = percentOfMaxHP\\n    end\\n    \\n    return text1, text2\\nend",
    ["yOffset"] = -150.49990844727,
    ["anchorPoint"] = "CENTER",
    ["cooldownSwipe"] = true,
    ["customTextUpdate"] = "update",
    ["url"] = "https://wago.io/IgnorePainTracker/16",
    ["actions"] = {
        ["start"] = {
            ["custom"] = "aura_env.hasBloodsport = aura_env.countAzeriteTrait(279172) >= 1",
            ["do_custom"] = true,
        },
        ["init"] = {
            ["custom"] = "-- by Marok (v2.2.0)\\n\\nlocal numberOfDecimalPlaces = false\\nif aura_env.config.textOptions.numberOfDecimalPlaces == 2 then\\n    numberOfDecimalPlaces = 0\\nelseif aura_env.config.textOptions.numberOfDecimalPlaces == 3 then\\n    numberOfDecimalPlaces = 1\\nelseif aura_env.config.textOptions.numberOfDecimalPlaces == 4 then\\n    numberOfDecimalPlaces = 2\\nelseif aura_env.config.textOptions.numberOfDecimalPlaces == 5 then\\n    numberOfDecimalPlaces = 3\\nend\\n\\naura_env.setVisuals = function(r,g,b,a, glow)\\n    \\n    local region = aura_env.region\\n    \\n    if aura_env.config.textOptions.colorText1 then\\n        region.stacks:SetTextColor(r,g,b,a)\\n    end\\n    \\n    if aura_env.config.textOptions.colorText2 then\\n        region.text2:SetTextColor(r,g,b,a)\\n    end\\n    \\n    if aura_env.config.iconOptions.glowCondition ~= 1 then\\n        region:SetGlow(glow)\\n    end\\nend\\n\\naura_env.shortenNumber = function(number)\\n    \\n    local shortenedNumber = number\\n    \\n    local wasNegative = false\\n    if number < 0 then\\n        number = number * -1\\n        wasNegative = true\\n    end\\n    \\n    local suffix = \\\"\\\"\\n    if number >= 1000000 then\\n        shortenedNumber = shortenedNumber / 1000000\\n        suffix = \\\"m\\\"\\n    elseif number >= 1000 then\\n        shortenedNumber = shortenedNumber / 1000\\n        suffix = \\\"k\\\"\\n    end\\n    \\n    if not numberOfDecimalPlaces then\\n        \\n        if shortenedNumber >= 100 then\\n            shortenedNumber = string.format(\\\"%.0f\\\", shortenedNumber)\\n        elseif shortenedNumber >= 10 then\\n            shortenedNumber = string.format(\\\"%.1f\\\", shortenedNumber)\\n        elseif shortenedNumber >= 1 then\\n            shortenedNumber = string.format(\\\"%.2f\\\", shortenedNumber)\\n        end\\n        \\n    else\\n        \\n        if number >= 1000 then\\n            shortenedNumber = string.format(\\\"%.\\\"..numberOfDecimalPlaces..\\\"f\\\", shortenedNumber)\\n        end\\n    end\\n    \\n    if aura_env.config.textOptions.dontShortenThousands and (number >= 1000 and number < 10000) then\\n        if wasNegative then\\n           number = number * -1 \\n        end\\n        return number\\n    else\\n        return shortenedNumber..suffix\\n    end\\nend\\n\\naura_env.shortenPercent = function(number)\\n    \\n    local shortenedNumber = number\\n    \\n    shortenedNumber = string.format(\\\"%.\\\"..aura_env.config.textOptions.percentNumOfDecimalPlaces..\\\"f\\\", shortenedNumber)\\n    \\n    if number <= 0 then\\n        shortenedNumber = 0\\n    end\\n    \\n    return shortenedNumber..\\\"%\\\"\\nend\\n\\n-- Thank you to Buds on wago for this function.\\n\\naura_env.countAzeriteTrait = function(spellId)\\n    \\n    local count = 0\\n    local azeriteItemLocation = C_AzeriteItem.FindActiveAzeriteItem()\\n    if (not azeriteItemLocation) then return 0 end\\n    \\n    local azeritePowerLevel = C_AzeriteItem.GetPowerLevel(azeriteItemLocation)\\n    local specID = GetSpecializationInfo(GetSpecialization())\\n    \\n    for slot = 1, 5, 2 do\\n        local item = Item:CreateFromEquipmentSlot(slot)\\n        if (not item:IsItemEmpty()) then\\n            local itemLocation = item:GetItemLocation()\\n            if (C_AzeriteEmpoweredItem.IsAzeriteEmpoweredItem(itemLocation)) then\\n                local tierInfo = C_AzeriteEmpoweredItem.GetAllTierInfo(itemLocation)\\n                for tier, info in next, tierInfo do\\n                    if (info.unlockLevel <= azeritePowerLevel) then\\n                        for _, powerID in next, info.azeritePowerIDs do\\n                            if C_AzeriteEmpoweredItem.IsPowerSelected(itemLocation, powerID)\\n                            and C_AzeriteEmpoweredItem.IsPowerAvailableForSpec(powerID, specID)\\n                            then\\n                                local powerInfo = C_AzeriteEmpoweredItem.GetPowerInfo(powerID)\\n                                if powerInfo.spellID == spellId then\\n                                    count = count + 1\\n                                end\\n                            end\\n                        end\\n                    end\\n                end\\n            end\\n        end\\n    end\\n    return count\\nend\\n\\naura_env.hasBloodsport = aura_env.countAzeriteTrait(279172) >= 1",
            ["do_custom"] = true,
        },
        ["finish"] = {
        },
    },
    ["useglowColor"] = false,
    ["internalVersion"] = 24,
    ["glowXOffset"] = 0,
    ["animation"] = {
        ["start"] = {
            ["type"] = "none",
            ["duration_type"] = "seconds",
        },
        ["main"] = {
            ["type"] = "none",
            ["duration_type"] = "seconds",
        },
        ["finish"] = {
            ["type"] = "none",
            ["duration_type"] = "seconds",
        },
    },
    ["tocversion"] = 80205,
    ["desc"] = "by Marok - <Potent> Mal'Ganis-US",
    ["glowColor"] = {
        [1] = 1,
        [2] = 1,
        [3] = 1,
        [4] = 1,
    },
    ["xOffset"] = -40.83349609375,
    ["version"] = 16,
    ["subRegions"] = {
        [1] = {
            ["text_shadowXOffset"] = 0,
            ["type"] = "subtext",
            ["text_text"] = "%c1",
            ["text_color"] = {
                [1] = 1,
                [2] = 1,
                [3] = 1,
                [4] = 1,
            },
            ["text_font"] = "Friz Quadrata TT",
            ["text_shadowColor"] = {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            ["text_shadowYOffset"] = 0,
            ["text_selfPoint"] = "AUTO",
            ["text_fontType"] = "OUTLINE",
            ["text_visible"] = true,
            ["text_anchorPoint"] = "CENTER",
            ["anchorYOffset"] = 0,
            ["text_justify"] = "CENTER",
            ["text_fontSize"] = 15,
            ["anchorXOffset"] = 0,
            ["rotateText"] = "NONE",
        },
        [2] = {
            ["text_shadowXOffset"] = 0,
            ["type"] = "subtext",
            ["text_text"] = "%c2",
            ["text_color"] = {
                [1] = 1,
                [2] = 1,
                [3] = 1,
                [4] = 1,
            },
            ["text_font"] = "Friz Quadrata TT",
            ["text_shadowColor"] = {
                [1] = 0,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            ["text_shadowYOffset"] = 0,
            ["text_selfPoint"] = "AUTO",
            ["text_fontType"] = "OUTLINE",
            ["text_visible"] = true,
            ["text_anchorPoint"] = "OUTER_TOP",
            ["anchorYOffset"] = 0,
            ["text_justify"] = "CENTER",
            ["text_fontSize"] = 15,
            ["anchorXOffset"] = 0,
            ["rotateText"] = "NONE",
        },
    },
    ["height"] = 50,
    ["selfPoint"] = "CENTER",
    ["glowLines"] = 8,
    ["icon"] = true,
    ["glowFrequency"] = 0.25,
    ["stickyDuration"] = false,
    ["cooldownEdge"] = false,
    ["glowType"] = "buttonOverlay",
    ["glowThickness"] = 1,
    ["authorOptions"] = {
        [1] = {
            ["subOptions"] = {
                [1] = {
                    ["type"] = "space",
                    ["variableWidth"] = false,
                    ["width"] = 2,
                },
                [2] = {
                    ["type"] = "description",
                    ["text"] = "Text Output",
                    ["fontSize"] = "medium",
                    ["width"] = 2,
                },
                [3] = {
                    ["type"] = "description",
                    ["text"] = "Text 1 and Text 2 are the two text fields that appear on the icon. By default, Text 1 is centered on the icon and Text 2 is on top and outside the icon.\\n\\nabsorb - Displays your remaining Ignore Pain absorb amount.\\npercent - Displays at what percent of the Ignore Pain cap you are at.\\nadditional - Displays how much Ignore Pain absorb you will gain by casting it.\\npercentofhp - Displays the % of your max health that Ignore Pain is making up.\\nnone - Displays nothing.",
                    ["fontSize"] = "small",
                    ["width"] = 2,
                },
                [4] = {
                    ["desc"] = "Controls what is displayed in the first text field.",
                    ["type"] = "select",
                    ["default"] = 1,
                    ["name"] = "Text 1",
                    ["values"] = {
                        [1] = "absorb",
                        [2] = "percent",
                        [3] = "additional",
                        [4] = "percentofhp",
                        [5] = "none",
                    },
                    ["useDesc"] = true,
                    ["key"] = "text1",
                    ["width"] = 1,
                },
                [5] = {
                    ["desc"] = "Controls what is displayed in the second text field.",
                    ["type"] = "select",
                    ["default"] = 5,
                    ["name"] = "Text 2",
                    ["values"] = {
                        [1] = "absorb",
                        [2] = "percent",
                        [3] = "additional",
                        [4] = "percentofhp",
                        [5] = "none",
                    },
                    ["useDesc"] = true,
                    ["key"] = "text2",
                    ["width"] = 1,
                },
                [6] = {
                    ["type"] = "space",
                    ["variableWidth"] = false,
                    ["width"] = 1,
                },
                [7] = {
                    ["type"] = "description",
                    ["text"] = "Text Color Toggle",
                    ["fontSize"] = "medium",
                    ["width"] = 2,
                },
                [8] = {
                    ["type"] = "description",
                    ["text"] = "Controls whether or not Text 1/Text 2 are colored according to the clip/capping rules. If unchecked, the text remains white (or whatever color you set in the Display tab).",
                    ["fontSize"] = "small",
                    ["width"] = 2,
                },
                [9] = {
                    ["type"] = "toggle",
                    ["key"] = "colorText1",
                    ["desc"] = "",
                    ["default"] = true,
                    ["useDesc"] = false,
                    ["name"] = "Text 1 Coloring",
                    ["width"] = 1,
                },
                [10] = {
                    ["type"] = "toggle",
                    ["key"] = "colorText2",
                    ["desc"] = "",
                    ["default"] = false,
                    ["useDesc"] = false,
                    ["name"] = "Text 2 Coloring",
                    ["width"] = 1,
                },
                [11] = {
                    ["type"] = "space",
                    ["variableWidth"] = false,
                    ["width"] = 1,
                },
                [12] = {
                    ["type"] = "description",
                    ["text"] = "Text Color",
                    ["fontSize"] = "medium",
                    ["width"] = 2,
                },
                [13] = {
                    ["type"] = "description",
                    ["text"] = "Controls the text color for each status of Ignore Pain.",
                    ["fontSize"] = "small",
                    ["width"] = 2,
                },
                [14] = {
                    ["type"] = "color",
                    ["key"] = "fullCastColor",
                    ["desc"] = "This is the text color you will see when casting Ignore Pain grants you full absorb.",
                    ["default"] = {
                        [1] = 1,
                        [2] = 1,
                        [3] = 1,
                        [4] = 1,
                    },
                    ["useDesc"] = true,
                    ["name"] = "Full Cast Color",
                    ["width"] = 0.6,
                },
                [15] = {
                    ["type"] = "color",
                    ["key"] = "capColor",
                    ["desc"] = "This is the text color you will see when casting Ignore Pain grants you partial absorb.",
                    ["default"] = {
                        [1] = 1,
                        [2] = 1,
                        [3] = 0,
                        [4] = 1,
                    },
                    ["useDesc"] = true,
                    ["name"] = "Cap Color",
                    ["width"] = 0.6,
                },
                [16] = {
                    ["type"] = "color",
                    ["key"] = "clipColor",
                    ["desc"] = "This is the text color you will see when casting Ignore Pain grants you no absorb or causes you to lose absorb.",
                    ["default"] = {
                        [1] = 1,
                        [2] = 0,
                        [3] = 0,
                        [4] = 1,
                    },
                    ["useDesc"] = true,
                    ["name"] = "Clip Color",
                    ["width"] = 0.6,
                },
                [17] = {
                    ["type"] = "space",
                    ["variableWidth"] = false,
                    ["width"] = 1,
                },
                [18] = {
                    ["type"] = "description",
                    ["text"] = "Full Cast Threshold",
                    ["fontSize"] = "medium",
                    ["width"] = 2,
                },
                [19] = {
                    ["type"] = "description",
                    ["text"] = "Controls the percentage of a full cast needed to still be considered a full cast. For example, when set to 75%, an Ignore Pain cast that will grant 75% of its absorb or more will still be considered a full cast.",
                    ["fontSize"] = "small",
                    ["width"] = 2,
                },
                [20] = {
                    ["type"] = "range",
                    ["useDesc"] = false,
                    ["max"] = 1,
                    ["step"] = 0.05,
                    ["width"] = 1,
                    ["min"] = 0.05,
                    ["key"] = "thresholdPerc",
                    ["name"] = "Threshold Percentage",
                    ["default"] = 0.75,
                },
                [21] = {
                    ["type"] = "space",
                    ["variableWidth"] = false,
                    ["height"] = 1,
                    ["width"] = 1,
                    ["useHeight"] = false,
                },
                [22] = {
                    ["type"] = "description",
                    ["text"] = "Text Formatting",
                    ["fontSize"] = "medium",
                    ["width"] = 2,
                },
                [23] = {
                    ["type"] = "description",
                    ["text"] = "Shorten Text, Number of Decimal Places, and Don't Shorten Thousands apply to the \\\"absorb\\\" and \\\"additional\\\" text outputs.\\n\\nPercent - Number of Decimal Places applies to the \\\"percent\\\" and \\\"percentofhp\\\" text outputs.",
                    ["fontSize"] = "small",
                    ["width"] = 2,
                },
                [24] = {
                    ["type"] = "toggle",
                    ["key"] = "shortenText",
                    ["desc"] = "Shortens text from 13,500 to 13.5k, for example. By default, text is always shortened to three numbers. That is, 5,500 is shortened to 5.50k, 15,500 is shortened to 15.5k.",
                    ["default"] = true,
                    ["useDesc"] = true,
                    ["name"] = "Shorten Text",
                    ["width"] = 1,
                },
                [25] = {
                    ["desc"] = "Allows you to force a certain number of decimal places to always be displayed. This option has no effect if Shorten Text isn't enabled.",
                    ["type"] = "select",
                    ["default"] = 1,
                    ["values"] = {
                        [1] = "default",
                        [2] = "0",
                        [3] = "1",
                        [4] = "2",
                        [5] = "3",
                    },
                    ["key"] = "numberOfDecimalPlaces",
                    ["useDesc"] = true,
                    ["name"] = "Number of Decimal Places",
                    ["width"] = 1,
                },
                [26] = {
                    ["type"] = "toggle",
                    ["key"] = "dontShortenThousands",
                    ["desc"] = "Displays absorb amounts between 1,000 and 10,000 without shortening them. For example, 5,000 shows as 5,000, but 12,000 shows as 12.0k (or according to Number of Decimal Places).",
                    ["default"] = false,
                    ["useDesc"] = true,
                    ["name"] = "Don't Shorten Thousands",
                    ["width"] = 1,
                },
                [27] = {
                    ["type"] = "range",
                    ["useDesc"] = true,
                    ["max"] = 2,
                    ["step"] = 1,
                    ["width"] = 1,
                    ["min"] = 0,
                    ["name"] = "Percent - Number of Decimal Places",
                    ["desc"] = "Sets the number of decimal places to be displayed.",
                    ["key"] = "percentNumOfDecimalPlaces",
                    ["default"] = 0,
                },
            },
            ["type"] = "group",
            ["useDesc"] = false,
            ["width"] = 2,
            ["useCollapse"] = true,
            ["key"] = "textOptions",
            ["name"] = "Text Options",
            ["limitType"] = "none",
            ["groupType"] = "simple",
            ["collapse"] = false,
            ["size"] = 10,
        },
        [2] = {
            ["subOptions"] = {
                [1] = {
                    ["type"] = "space",
                    ["variableWidth"] = false,
                    ["width"] = 1,
                },
                [2] = {
                    ["type"] = "description",
                    ["text"] = "Icon Glow",
                    ["fontSize"] = "medium",
                    ["width"] = 2,
                },
                [3] = {
                    ["type"] = "description",
                    ["text"] = "Controls under what condition the icon glows.\\n\\nNo Glow - Icon glow is disabled.\\nFull Cast - When your next cast will grant its full absorb.\\nPartial Cast - When your next cast will grant a portion of its absorb (i.e. cap).\\nFull & Partial - When your next cast will grant full or partial absorb.",
                    ["fontSize"] = "small",
                    ["width"] = 2,
                },
                [4] = {
                    ["desc"] = "",
                    ["type"] = "select",
                    ["default"] = 1,
                    ["name"] = "Glow Condition",
                    ["values"] = {
                        [1] = "No Glow",
                        [2] = "Full Cast",
                        [3] = "Partial Cast",
                        [4] = "Full & Partial",
                    },
                    ["useDesc"] = false,
                    ["key"] = "glowCondition",
                    ["width"] = 1,
                },
                [5] = {
                    ["type"] = "space",
                    ["variableWidth"] = false,
                    ["width"] = 1,
                },
                [6] = {
                    ["type"] = "description",
                    ["text"] = "By default, the icon is saturated (has color) when Ignore Pain is up, and desaturated when Ignore Pain is down. Enabling this option will instead saturate the icon when you have enough Rage to cast Ignore Pain and desaturate it when you don't.",
                    ["fontSize"] = "small",
                    ["width"] = 2,
                },
                [7] = {
                    ["type"] = "toggle",
                    ["key"] = "saturateBasedOnRage",
                    ["desc"] = "",
                    ["default"] = false,
                    ["useDesc"] = false,
                    ["name"] = "Saturate Based on Rage",
                    ["width"] = 1,
                },
            },
            ["type"] = "group",
            ["useDesc"] = false,
            ["width"] = 1,
            ["useCollapse"] = true,
            ["key"] = "iconOptions",
            ["name"] = "Icon Options",
            ["limitType"] = "none",
            ["groupType"] = "simple",
            ["collapse"] = false,
            ["size"] = 10,
        },
    },
    ["triggers"] = {
        [1] = {
            ["trigger"] = {
                ["type"] = "aura2",
                ["auraspellids"] = {
                    [1] = "190456",
                },
                ["matchesShowOn"] = "showAlways",
                ["event"] = "Health",
                ["names"] = {
                },
                ["unit"] = "player",
                ["spellIds"] = {
                },
                ["subeventSuffix"] = "_CAST_START",
                ["combineMode"] = "showHighest",
                ["useExactSpellId"] = true,
                ["subeventPrefix"] = "SPELL",
                ["debuffType"] = "HELPFUL",
            },
            ["untrigger"] = {
            },
        },
        ["activeTriggerMode"] = -10,
    },
    ["uid"] = "xNtMlJDFW1N",
    ["regionType"] = "icon",
    ["glowLength"] = 10,
    ["glowYOffset"] = 0,
    ["alpha"] = 1,
    ["load"] = {
        ["use_class"] = true,
        ["use_never"] = false,
        ["use_spec"] = true,
        ["use_combat"] = true,
        ["class"] = {
            ["single"] = "WARRIOR",
            ["multi"] = {
            },
        },
        ["spec"] = {
            ["single"] = 3,
            ["multi"] = {
            },
        },
        ["size"] = {
            ["multi"] = {
            },
        },
    },
    ["auto"] = true,
    ["zoom"] = 0,
    ["cooldownTextDisabled"] = true,
    ["semver"] = "2.2.0",
    ["glowScale"] = 1,
    ["id"] = "Ignore Pain Tracker",
    ["keepAspectRatio"] = false,
    ["frameStrata"] = 1,
    ["anchorFrameType"] = "SCREEN",
    ["width"] = 50,
    ["config"] = {
        ["iconOptions"] = {
            ["saturateBasedOnRage"] = false,
            ["glowCondition"] = 1,
        },
        ["textOptions"] = {
            ["numberOfDecimalPlaces"] = 1,
            ["text2"] = 5,
            ["dontShortenThousands"] = false,
            ["clipColor"] = {
                [1] = 1,
                [2] = 0,
                [3] = 0,
                [4] = 1,
            },
            ["capColor"] = {
                [1] = 1,
                [2] = 1,
                [3] = 0,
                [4] = 1,
            },
            ["shortenText"] = true,
            ["thresholdPerc"] = 0.75,
            ["fullCastColor"] = {
                [1] = 1,
                [2] = 1,
                [3] = 1,
                [4] = 1,
            },
            ["colorText1"] = true,
            ["colorText2"] = false,
            ["text1"] = 1,
            ["percentNumOfDecimalPlaces"] = 0,
        },
    },
    ["inverse"] = false,
    ["desaturate"] = false,
    ["conditions"] = {
    },
    ["cooldown"] = true,
    ["glowBorder"] = false,
}